# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: America After 3PM
description: America After 3PM

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess', 'national.html']
